' Generated by TinyPG v1.1 available at www.codeproject.com

Imports System
Imports System.Collections.Generic
Imports System.Text


Namespace TinyPG
#Region "ParseTree"
    Public Class ParseErrors 
        Inherits List(Of ParseError)
    End Class

    Public Class ParseError 
        Private m_message As String
        Private m_code As Integer
        Private m_line As Integer
        Private m_col As Integer
        Private m_pos As Integer
        Private m_length As Integer

        Public ReadOnly Property Code() As Integer
            Get
                Return m_code
            End Get
        End Property

        Public ReadOnly Property Line() As Integer
            Get
                Return m_line
            End Get
        End Property

        Public ReadOnly Property Column() As Integer
            Get
                Return m_col
            End Get
        End Property

        Public ReadOnly Property Position() As Integer
            Get
                Return m_pos
            End Get
        End Property

        Public ReadOnly Property Length() As Integer
            Get
                Return m_length
            End Get
        End Property

        Public ReadOnly Property Message() As String
            Get
                Return m_message
            End Get
        End Property

        Public Sub New(ByVal message As String, ByVal code As Integer, ByVal node As ParseNode)
            Me.New(message, code, 0, node.Token.StartPos, node.Token.StartPos, node.Token.Length)
        End Sub

        Public Sub New(ByVal message As String, ByVal code As Integer, ByVal line As Integer, ByVal col As Integer, ByVal pos As Integer, ByVal length As Integer)
            m_message = message
            m_code = code
            m_line = line
            m_col = col
            m_pos = pos
            m_length = length
        End Sub
    End Class

    ' rootlevel of the node tree
    Partial Public Class ParseTree
        Inherits ParseNode

        Public Errors As ParseErrors

        Public Skipped As List(Of Token)

        Public Sub New()
            MyBase.New(New Token(), "ParseTree")
            Token.Type = TokenType.Start
            Token.Text = "Root"
            Skipped = New List(Of Token)()
            Errors = New ParseErrors()
        End Sub

        Public Function PrintTree() As String
    Dim sb As New StringBuilder()
    Dim indent As Integer = 0
            PrintNode(sb, Me, indent)
            Return sb.ToString()
        End Function

    Private Sub PrintNode(ByVal sb As StringBuilder, ByVal node As ParseNode, ByVal indent As Integer)

        Dim space As String = "".PadLeft(indent, " "c)

        sb.Append(space)
        sb.AppendLine(node.Text)

        For Each n As ParseNode In node.Nodes
            PrintNode(sb, n, indent + 2)
        Next
    End Sub

    ''' <summary>
    ''' this is the entry point for executing and evaluating the parse tree.
    ''' </summary>
    ''' <param name="paramlist">additional optional input parameters</param>
    ''' <returns>the output of the evaluation function</returns>
    Public Overloads Function Eval(ByVal ParamArray paramlist As Object()) As Object
        Return Nodes(0).Eval(Me, paramlist)
    End Function
    End Class
#End Region

#Region "ParseNode"
    Partial Public Class ParseNode 
        Protected m_text As String
        Protected m_nodes As List(Of ParseNode)
        

        Public ReadOnly Property Nodes() As List(Of ParseNode)
            Get
                Return m_nodes
            End Get
        End Property

        
        Public Parent As ParseNode
        Public Token As Token
        ' the token/rule
        Public Property Text() As String
            ' text to display in parse tree 
            Get
                Return m_text
            End Get
            Set(ByVal value As String)
                m_text = value
            End Set
        End Property

        Public Overridable Function CreateNode(ByVal token As Token, ByVal text As String) As ParseNode
            Dim node As New ParseNode(token, text)
            node.Parent = Me
            Return node
        End Function

        Protected Sub New(ByVal token As Token, ByVal text As String)
            Me.Token = token
            m_text = text
            m_nodes = New List(Of ParseNode)()
        End Sub

        Protected Function GetValue(ByVal tree As ParseTree, ByVal type As TokenType, ByVal index As Integer) As Object
            Return GetValueByRef(tree, type, index)
        End Function

        Protected Function GetValueByRef(ByVal tree As ParseTree, ByVal type As TokenType, ByRef index As Integer) As Object
            Dim o As Object = Nothing
            If index < 0 Then
                Return o
            End If

    ' left to right
            For Each node As ParseNode In nodes
                If node.Token.Type = type Then
                    System.Math.Max(System.Threading.Interlocked.Decrement(index), index + 1)
                    If index < 0 Then
                        o = node.Eval(tree)
                        Exit For
                    End If
                End If
            Next
            Return o
        End Function

    ''' <summary>
    ''' this implements the evaluation functionality, cannot be used directly
    ''' </summary>
    ''' <param name="tree">the parsetree itself</param>
    ''' <param name="paramlist">optional input parameters</param>
    ''' <returns>a partial result of the evaluation</returns>
    Friend Function Eval(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
        Dim Value As Object = Nothing

        Select Case Token.Type
                Case TokenType.Start
                    Value = EvalStart(tree, paramlist)
                    Exit Select
                Case TokenType.Directive
                    Value = EvalDirective(tree, paramlist)
                    Exit Select
                Case TokenType.NameValue
                    Value = EvalNameValue(tree, paramlist)
                    Exit Select
                Case TokenType.ExtProduction
                    Value = EvalExtProduction(tree, paramlist)
                    Exit Select
                Case TokenType.Attribute
                    Value = EvalAttribute(tree, paramlist)
                    Exit Select
                Case TokenType.Params
                    Value = EvalParams(tree, paramlist)
                    Exit Select
                Case TokenType.Param
                    Value = EvalParam(tree, paramlist)
                    Exit Select
                Case TokenType.Production
                    Value = EvalProduction(tree, paramlist)
                    Exit Select
                Case TokenType.Rule
                    Value = EvalRule(tree, paramlist)
                    Exit Select
                Case TokenType.Subrule
                    Value = EvalSubrule(tree, paramlist)
                    Exit Select
                Case TokenType.ConcatRule
                    Value = EvalConcatRule(tree, paramlist)
                    Exit Select
                Case TokenType.Symbol
                    Value = EvalSymbol(tree, paramlist)
                    Exit Select

            Case Else
                Value = Token.Text
                Exit Select
        End Select
        Return Value
        End Function

        Protected Overridable Function EvalStart(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Return "Could not interpret input; no semantics implemented."
        End Function

        Protected Overridable Function EvalDirective(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalNameValue(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalExtProduction(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalAttribute(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalParams(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalParam(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalProduction(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalRule(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalSubrule(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalConcatRule(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function

        Protected Overridable Function EvalSymbol(ByVal tree As ParseTree, ByVal ParamArray paramlist As Object()) As Object
            Throw New NotImplementedException()
        End Function



    End Class
#End Region
End Namespace

